# build layer
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

COPY WeatherBuddy.Api ./
RUN dotnet clean
RUN dotnet restore
RUN dotnet publish -c Release -o out --no-restore

# final layer
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "WeatherBuddy.Api.dll"]
